~/Applications/ffmpeg -i gif/epidermis.gif mp4/epidermis.mp4
~/Applications/ffmpeg -i gif/macrophage.gif mp4/macrophage.mp4
~/Applications/ffmpeg -i gif/notocord.gif mp4/notocord.mp4
~/Applications/ffmpeg -i gif/stg11.gif mp4/stg11.mp4
~/Applications/ffmpeg -i gif/stg12.gif mp4/stg12.mp4
~/Applications/ffmpeg -i gif/stg5.gif mp4/stg5.mp4
~/Applications/ffmpeg -i gif/wt_stg10_ecad_AbdB_10x.gif mp4/wt_stg10_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg11_ecad_AbdB_10x.gif mp4/wt_stg11_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg12_ecad_AbdB_10x.gif mp4/wt_stg12_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg13_ecad_AbdB_10x.gif mp4/wt_stg13_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg15_ecad_AbdB_10x.gif mp4/wt_stg15_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg16_ecad_AbdB_10x.gif mp4/wt_stg16_ecad_AbdB_10x.mp4
~/Applications/ffmpeg -i gif/wt_stg16_ecad_AbdB_RGB_0.25.gif mp4/wt_stg16_ecad_AbdB_RGB_0.25.mp4
