mv C1-genotypeA_eve_bgal_z_0.jpg C1-genotypeA_eve_bgal_z_0.jpg
mv C1-genotypeA_eve_bgal_z_1.jpg C1-genotypeB_eve_bgal_z_1.jpg
mv C1-genotypeA_eve_bgal_z_2.jpg C1-genotypeB_eve_bgal_z_2.jpg
mv C1-genotypeA_eve_bgal_z_3.jpg C1-genotypeB_eve_bgal_z_3.jpg
mv C1-genotypeA_eve_bgal_z_4.jpg C1-genotypeB_eve_bgal_z_4.jpg
mv C1-genotypeA_eve_bgal_z_5.jpg C1-genotypeB_eve_bgal_z_5.jpg
mv C1-genotypeA_eve_bgal_z_6.jpg C1-genotypeB_eve_bgal_z_6.jpg
mv C1-genotypeA_eve_bgal_z_7.jpg C1-genotypeB_eve_bgal_z_7.jpg
mv C1-genotypeA_eve_bgal_z_8.jpg C1-genotypeB_eve_bgal_z_8.jpg
mv C1-genotypeA_eve_bgal_z_9.jpg C1-genotypeB_eve_bgal_z_9.jpg
mv C2-genotypeA_eve_bgal_z_0.jpg C2-genotypeB_eve_bgal_z_0.jpg
mv C2-genotypeA_eve_bgal_z_1.jpg C2-genotypeB_eve_bgal_z_1.jpg
mv C2-genotypeA_eve_bgal_z_2.jpg C2-genotypeB_eve_bgal_z_2.jpg
mv C2-genotypeA_eve_bgal_z_3.jpg C2-genotypeB_eve_bgal_z_3.jpg
mv C2-genotypeA_eve_bgal_z_4.jpg C2-genotypeB_eve_bgal_z_4.jpg
mv C2-genotypeA_eve_bgal_z_5.jpg C2-genotypeB_eve_bgal_z_5.jpg
mv C2-genotypeA_eve_bgal_z_6.jpg C2-genotypeB_eve_bgal_z_6.jpg
mv C2-genotypeA_eve_bgal_z_7.jpg C2-genotypeB_eve_bgal_z_7.jpg
mv C2-genotypeA_eve_bgal_z_8.jpg C2-genotypeB_eve_bgal_z_8.jpg
mv C2-genotypeA_eve_bgal_z_9.jpg C2-genotypeB_eve_bgal_z_9.jpg
mv genotypeA_eve_bgal_z_0.jpg genotypeB_eve_bgal_z_0.jpg
mv genotypeA_eve_bgal_z_1.jpg genotypeB_eve_bgal_z_1.jpg
mv genotypeA_eve_bgal_z_2.jpg genotypeB_eve_bgal_z_2.jpg
mv genotypeA_eve_bgal_z_3.jpg genotypeB_eve_bgal_z_3.jpg
mv genotypeA_eve_bgal_z_4.jpg genotypeB_eve_bgal_z_4.jpg
mv genotypeA_eve_bgal_z_5.jpg genotypeB_eve_bgal_z_5.jpg
mv genotypeA_eve_bgal_z_6.jpg genotypeB_eve_bgal_z_6.jpg
mv genotypeA_eve_bgal_z_7.jpg genotypeB_eve_bgal_z_7.jpg
mv genotypeA_eve_bgal_z_8.jpg genotypeB_eve_bgal_z_8.jpg
mv genotypeA_eve_bgal_z_9.jpg genotypeB_eve_bgal_z_9.jpg
